### ISSUE TITLE
Typo in activity_main.xml

### ISSUE THREAD

**Issue by brian-norman** [googlecodelabs/android-dagger#13]
I think the settings button id should be `@+id/settings` instead of `@+id/logout` 😃

**Comment by manuelvicnt** [comment]
Thanks for reporting! This will get fixed with #16

**Comment by THELEMITED** [comment]
Wow you got fired because a police officer flagged me down during a navy post war operation criminally funded by terrorists accused me of being a drug dealer. And I faced the death penalty in the Philippines for selling drugs to myself as a federal officer at the fbi.

Nevermind, they were just gay and are being hung for treason. It's titled ../runc.obs(mph)
